Script started on 2022-02-28 08:43:39-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="104" LINES="49"]
]0;srangel@compute:~/2211/Assignments/Assignment3[?2004h[srangel@compute Assignment3]$ ./Assignment3
[?2004lPlease enter your integers separated by spaces: 5 1 2 0 3 5 6 0 5     5 9 0 8 0 4   0 5 0

Part 1: 
    Your array is: 5 1 2 0 3 5 6 0 5 5 9 0 8 0 4 0 5 0
    Your array has 18 elements
    The size of the array is 72 bytes
 
 Part 2: 
    Your array in reverse is: 0 5 0 4 0 8 0 9 5 5 0 6 5 3 0 2 1 5
 
 Part 3: 
    The smallest value in your array is: 0
 
 Part 4: 
    The sum of all values in your array is 58
 
 Part 5: 
    Your array with first and last element switched is: 0 1 2 0 3 5 6 0 5 5 9 0 8 0 4 0 5 5
 
 Part 6: 
    Your array in sorted order is: 0 0 0 0 0 0 1 2 3 4 5 5 5 5 5 6 8 9]0;srangel@compute:~/2211/Assignments/Assignment3[?2004h[srangel@compute Assignment3]$ ./Assignment3
[?2004lPlease enter your integers separated by spaces: 5 6      9   0 8 0   3 7 9 0       8 9999999 6

Part 1: 
    Your array is: 5 6 9 0 8 0 3 7 9 0 8 9999999 6
    Your array has 13 elements
    The size of the array is 52 bytes
 
 Part 2: 
    Your array in reverse is: 6 9999999 8 0 9 7 3 0 8 0 9 6 5
 
 Part 3: 
    The smallest value in your array is: 0
 
 Part 4: 
    The sum of all values in your array is 10000060
 
 Part 5: 
    Your array with first and last element switched is: 6 6 9 0 8 0 3 7 9 0 8 9999999 5
 
 Part 6: 
    Your array in sorted order is: 0 0 0 3 5 6 6 7 8 8 9 9 9999999]0;srangel@compute:~/2211/Assignments/Assignment3[?2004h[srangel@compute Assignment3]$ exit
[?2004lexit

Script done on 2022-02-28 08:45:01-05:00 [COMMAND_EXIT_CODE="0"]
