Script started on 2022-02-08 22:46:07-05:00 [TERM="xterm-256color" TTY="/dev/pts/87" COLUMNS="104" LINES="49"]
]0;srangel@compute:~/2211/Assignments/Assignment2[?2004h[srangel@compute Assignment2]$ gcc -o intToEnglish intToEnglish.c
[?2004l]0;srangel@compute:~/2211/Assignments/Assignment2[?2004h[srangel@compute Assignment2]$ ./intToEnglish
[?2004lPlease enter a value (1-999, 0 to quit): 123
You entered: one hundred twenty three 
Please enter a value (1-999, 0 to quit): 001
You entered:  one 
Please enter a value (1-999, 0 to quit): 010
You entered:  ten 
Please enter a value (1-999, 0 to quit): 999
You entered: nine hundred ninety nine 
Please enter a value (1-999, 0 to quit): 1
You entered:  one 
Please enter a value (1-999, 0 to quit): 555
You entered: five hundred fifty five 
Please enter a value (1-999, 0 to quit): 666
You entered: six hundred sixty six 
Please enter a value (1-999, 0 to quit): 849
You entered: eight hundred fourty nine 
Please enter a value (1-999, 0 to quit): 0 -8
You entered an invalid number. 
Please enter a value (1-999, 0 to quit): 999999
You entered an invalid number. 
Please enter a value (1-999, 0 to quit): 0
You have exited the program. 
]0;srangel@compute:~/2211/Assignments/Assignment2[?2004h[srangel@compute Assignment2]$ exit
[?2004lexit

Script done on 2022-02-08 22:47:25-05:00 [COMMAND_EXIT_CODE="0"]
